package edu.temple.contacttracer.database.entity;

import android.content.Context;
import android.location.Location;
import android.util.Log;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.Serializable;
import java.util.UUID;

import edu.temple.contacttracer.support.PreferenceUtils;
import edu.temple.contacttracer.support.interfaces.GlobalStateManager;

@Entity(tableName = "contact_event")
public class ContactEvent implements Serializable {
    @PrimaryKey(autoGenerate = true)
    public int id;

    @NonNull
    public UUID uuid;

    @NonNull
    public Double latitude;

    @NonNull
    public Double longitude;

    @ColumnInfo(name = "sedentary_begin")
    @NonNull
    public Long sedentaryBegin;

    @ColumnInfo(name = "sedentary_end")
    @NonNull
    public Long sedentaryEnd;

    public ContactEvent(@NonNull UUID uuid, @NonNull Double latitude, @NonNull Double longitude, @NonNull Long sedentaryBegin, @NonNull Long sedentaryEnd) {
        this.uuid = uuid;
        this.latitude = latitude;
        this.longitude = longitude;
        this.sedentaryBegin = sedentaryBegin;
        this.sedentaryEnd = sedentaryEnd;
    }

    /**
     * Generate a contact event from the payload sent from FCM
     *
     * @param payload The payload as a JSON Object
     * @return The contact event
     * @throws JSONException Throws when the payload's structure is malformed
     */
    public static ContactEvent fromPayload(JSONObject payload) throws JSONException {
        UUID uuid = UUID.fromString(payload.getString("uuid"));
        Double latitude = payload.getDouble("latitude");
        Double longitude = payload.getDouble("longitude");
        Long sedentaryBegin = payload.getLong("sedentary_begin");
        Long sedentaryEnd = payload.getLong("sedentary_end");
        return new ContactEvent(uuid, latitude, longitude, sedentaryBegin, sedentaryEnd);
    }

    /**
     * Generate a location object from the latitude and longitude of the event
     *
     * @return A location object
     */
    public Location getLocation() {
        Location location = new Location("");
        location.setLatitude(latitude);
        location.setLongitude(longitude);
        return location;
    }

    /**
     * Validates the contact event
     * Verifies that:
     * - The event was not generated by the current device
     * - The event is currently close enough to be relevant
     *
     * @param ctx Access to some context object to access the global state
     * @return If the event is valid
     */
    public boolean validate(Context ctx) {
        GlobalStateManager global = (GlobalStateManager) ctx.getApplicationContext();

        if (global.getDb().uniqueIdDao().hasById(uuid)) {
            Log.d("Test", "Self contact event");
            return false; // Check if self
        }

        int maxDistance = PreferenceUtils.getTrackingDistance(ctx);
        Location currentLoc = global.getLastLocation();
        Location eventLoc = getLocation();
        if (currentLoc == null) {
            Log.d("Test", "No current location");
            return false; // Location never retrieved
        }
        Log.d("Test", "Distance to event: " + currentLoc.distanceTo(eventLoc));
        return currentLoc.distanceTo(eventLoc) <= maxDistance; // Check if too far

    }

    @NonNull
    @Override
    public String toString() {
        return "ContactEvent{" +
                "id=" + id +
                ", uuid=" + uuid +
                ", latitude=" + latitude +
                ", longitude=" + longitude +
                ", sedentaryBegin=" + sedentaryBegin +
                ", sedentaryEnd=" + sedentaryEnd +
                '}';
    }
}
