package edu.temple.contacttracer.database.entity;

import android.content.Context;

import androidx.annotation.NonNull;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import org.json.JSONException;
import org.json.JSONObject;

import java.util.UUID;

import edu.temple.contacttracer.support.LocationUtils;
import edu.temple.contacttracer.support.interfaces.GlobalStateManager;

@Entity(tableName = "contact_event")
public class ContactEvent {
    @PrimaryKey(autoGenerate = true)
    public int id;

    @NonNull
    public UUID uuid;

    @NonNull
    public Double latitude;

    @NonNull
    public Double longitude;

    @ColumnInfo(name = "sedentary_begin")
    @NonNull
    public Long sedentaryBegin;

    @ColumnInfo(name = "sedentary_end")
    @NonNull
    public Long sedentaryEnd;

    public ContactEvent(@NonNull UUID uuid, @NonNull Double latitude, @NonNull Double longitude, @NonNull Long sedentaryBegin, @NonNull Long sedentaryEnd) {
        this.uuid = uuid;
        this.latitude = latitude;
        this.longitude = longitude;
        this.sedentaryBegin = sedentaryBegin;
        this.sedentaryEnd = sedentaryEnd;
    }

    /**
     * Generate a contact event from the payload sent from FCM
     *
     * @param payload The payload as a JSON Object
     * @return The contact event
     * @throws JSONException Throws when the payload's structure is malformed
     */
    public static ContactEvent fromPayload(JSONObject payload) throws JSONException {
        UUID uuid = UUID.fromString(payload.getString("uuid"));
        Double latitude = payload.getDouble("latitude");
        Double longitude = payload.getDouble("longitude");
        Long sedentaryBegin = payload.getLong("sedentary_begin");
        Long sedentaryEnd = payload.getLong("sedentary_end");
        return new ContactEvent(uuid, latitude, longitude, sedentaryBegin, sedentaryEnd);
    }

    /**
     * Validates the contact event
     * Verifies that:
     * - The event was not generated by the current device
     * - The event is currently close enough to be relevant
     *
     * @param ctx Access to some context object to access the global state
     * @return If the event is valid
     */
    public boolean validate(Context ctx) {
        GlobalStateManager global = (GlobalStateManager) ctx.getApplicationContext();

        if (global.getDb().uniqueIdDao().hasById(uuid)) return false; // Check if self
        return LocationUtils.checkTracingDistance(ctx, latitude, longitude); // Check if too far
    }

    @NonNull
    @Override
    public String toString() {
        return "ContactEvent{" +
                "id=" + id +
                ", uuid=" + uuid +
                ", latitude=" + latitude +
                ", longitude=" + longitude +
                ", sedentaryBegin=" + sedentaryBegin +
                ", sedentaryEnd=" + sedentaryEnd +
                '}';
    }
}
